/** Países de América (Norte → Sur) + divisiones para Config Nexus. */

export type CountryCode =
  | 'CA'
  | 'US'
  | 'MX'
  | 'GT'
  | 'BZ'
  | 'SV'
  | 'HN'
  | 'NI'
  | 'CR'
  | 'PA'
  | 'CU'
  | 'DO'
  | 'HT'
  | 'JM'
  | 'TT'
  | 'BS'
  | 'BB'
  | 'PR'
  | 'CO'
  | 'VE'
  | 'GY'
  | 'SR'
  | 'BR'
  | 'EC'
  | 'PE'
  | 'BO'
  | 'PY'
  | 'CL'
  | 'AR'
  | 'UY';

export interface CountryDef {
  code: CountryCode;
  name: string;
  flag: string;
  stateLabel: string;
  states: string[];
}

/** Orden geográfico aproximado: Canadá → Cono Sur. */
export const COUNTRIES: CountryDef[] = [
  {
    code: 'CA',
    name: 'Canadá',
    flag: '🇨🇦',
    stateLabel: 'Provincia / territorio',
    states: [
      'Alberta',
      'British Columbia',
      'Manitoba',
      'New Brunswick',
      'Newfoundland and Labrador',
      'Northwest Territories',
      'Nova Scotia',
      'Nunavut',
      'Ontario',
      'Prince Edward Island',
      'Quebec',
      'Saskatchewan',
      'Yukon',
    ],
  },
  {
    code: 'US',
    name: 'Estados Unidos',
    flag: '🇺🇸',
    stateLabel: 'Estado',
    states: [
      'Alabama',
      'Alaska',
      'Arizona',
      'Arkansas',
      'California',
      'Colorado',
      'Connecticut',
      'Delaware',
      'Florida',
      'Georgia',
      'Hawaii',
      'Idaho',
      'Illinois',
      'Indiana',
      'Iowa',
      'Kansas',
      'Kentucky',
      'Louisiana',
      'Maine',
      'Maryland',
      'Massachusetts',
      'Michigan',
      'Minnesota',
      'Mississippi',
      'Missouri',
      'Montana',
      'Nebraska',
      'Nevada',
      'New Hampshire',
      'New Jersey',
      'New Mexico',
      'New York',
      'North Carolina',
      'North Dakota',
      'Ohio',
      'Oklahoma',
      'Oregon',
      'Pennsylvania',
      'Rhode Island',
      'South Carolina',
      'South Dakota',
      'Tennessee',
      'Texas',
      'Utah',
      'Vermont',
      'Virginia',
      'Washington',
      'West Virginia',
      'Wisconsin',
      'Wyoming',
      'District of Columbia',
      'Puerto Rico',
    ],
  },
  {
    code: 'MX',
    name: 'México',
    flag: '🇲🇽',
    stateLabel: 'Estado',
    states: [
      'Aguascalientes',
      'Baja California',
      'Baja California Sur',
      'Campeche',
      'Chiapas',
      'Chihuahua',
      'Ciudad de México',
      'Coahuila',
      'Colima',
      'Durango',
      'Estado de México',
      'Guanajuato',
      'Guerrero',
      'Hidalgo',
      'Jalisco',
      'Michoacán',
      'Morelos',
      'Nayarit',
      'Nuevo León',
      'Oaxaca',
      'Puebla',
      'Querétaro',
      'Quintana Roo',
      'San Luis Potosí',
      'Sinaloa',
      'Sonora',
      'Tabasco',
      'Tamaulipas',
      'Tlaxcala',
      'Veracruz',
      'Yucatán',
      'Zacatecas',
    ],
  },
  {
    code: 'GT',
    name: 'Guatemala',
    flag: '🇬🇹',
    stateLabel: 'Departamento',
    states: [
      'Alta Verapaz',
      'Baja Verapaz',
      'Chimaltenango',
      'Chiquimula',
      'El Progreso',
      'Escuintla',
      'Guatemala',
      'Huehuetenango',
      'Izabal',
      'Jalapa',
      'Jutiapa',
      'Petén',
      'Quetzaltenango',
      'Quiché',
      'Retalhuleu',
      'Sacatepéquez',
      'San Marcos',
      'Santa Rosa',
      'Sololá',
      'Suchitepéquez',
      'Totonicapán',
      'Zacapa',
    ],
  },
  {
    code: 'BZ',
    name: 'Belice',
    flag: '🇧🇿',
    stateLabel: 'Distrito',
    states: ['Belize', 'Cayo', 'Corozal', 'Orange Walk', 'Stann Creek', 'Toledo'],
  },
  {
    code: 'SV',
    name: 'El Salvador',
    flag: '🇸🇻',
    stateLabel: 'Departamento',
    states: [
      'Ahuachapán',
      'Cabañas',
      'Chalatenango',
      'Cuscatlán',
      'La Libertad',
      'La Paz',
      'La Unión',
      'Morazán',
      'San Miguel',
      'San Salvador',
      'San Vicente',
      'Santa Ana',
      'Sonsonate',
      'Usulután',
    ],
  },
  {
    code: 'HN',
    name: 'Honduras',
    flag: '🇭🇳',
    stateLabel: 'Departamento',
    states: [
      'Atlántida',
      'Choluteca',
      'Colón',
      'Comayagua',
      'Copán',
      'Cortés',
      'El Paraíso',
      'Francisco Morazán',
      'Gracias a Dios',
      'Intibucá',
      'Islas de la Bahía',
      'La Paz',
      'Lempira',
      'Ocotepeque',
      'Olancho',
      'Santa Bárbara',
      'Valle',
      'Yoro',
    ],
  },
  {
    code: 'NI',
    name: 'Nicaragua',
    flag: '🇳🇮',
    stateLabel: 'Departamento',
    states: [
      'Boaco',
      'Carazo',
      'Chinandega',
      'Chontales',
      'Estelí',
      'Granada',
      'Jinotega',
      'León',
      'Madriz',
      'Managua',
      'Masaya',
      'Matagalpa',
      'Nueva Segovia',
      'Río San Juan',
      'Rivas',
      'Costa Caribe Norte',
      'Costa Caribe Sur',
    ],
  },
  {
    code: 'CR',
    name: 'Costa Rica',
    flag: '🇨🇷',
    stateLabel: 'Provincia',
    states: ['San José', 'Alajuela', 'Cartago', 'Heredia', 'Guanacaste', 'Puntarenas', 'Limón'],
  },
  {
    code: 'PA',
    name: 'Panamá',
    flag: '🇵🇦',
    stateLabel: 'Provincia / comarca',
    states: [
      'Bocas del Toro',
      'Chiriquí',
      'Coclé',
      'Colón',
      'Darién',
      'Herrera',
      'Los Santos',
      'Panamá',
      'Panamá Oeste',
      'Veraguas',
      'Guna Yala',
      'Emberá-Wounaan',
      'Ngäbe-Buglé',
    ],
  },
  {
    code: 'CU',
    name: 'Cuba',
    flag: '🇨🇺',
    stateLabel: 'Provincia',
    states: [
      'Pinar del Río',
      'Artemisa',
      'La Habana',
      'Mayabeque',
      'Matanzas',
      'Cienfuegos',
      'Villa Clara',
      'Sancti Spíritus',
      'Ciego de Ávila',
      'Camagüey',
      'Las Tunas',
      'Holguín',
      'Granma',
      'Santiago de Cuba',
      'Guantánamo',
      'Isla de la Juventud',
    ],
  },
  {
    code: 'DO',
    name: 'República Dominicana',
    flag: '🇩🇴',
    stateLabel: 'Provincia',
    states: [
      'Distrito Nacional',
      'Azua',
      'Baoruco',
      'Barahona',
      'Dajabón',
      'Duarte',
      'Elías Piña',
      'El Seibo',
      'Espaillat',
      'Hato Mayor',
      'Hermanas Mirabal',
      'Independencia',
      'La Altagracia',
      'La Romana',
      'La Vega',
      'María Trinidad Sánchez',
      'Monseñor Nouel',
      'Monte Cristi',
      'Monte Plata',
      'Pedernales',
      'Peravia',
      'Puerto Plata',
      'Samaná',
      'San Cristóbal',
      'San José de Ocoa',
      'San Juan',
      'San Pedro de Macorís',
      'Sánchez Ramírez',
      'Santiago',
      'Santiago Rodríguez',
      'Santo Domingo',
      'Valverde',
    ],
  },
  {
    code: 'HT',
    name: 'Haití',
    flag: '🇭🇹',
    stateLabel: 'Departamento',
    states: [
      'Artibonite',
      'Centre',
      'Grand\'Anse',
      'Nippes',
      'Nord',
      'Nord-Est',
      'Nord-Ouest',
      'Ouest',
      'Sud',
      'Sud-Est',
    ],
  },
  {
    code: 'JM',
    name: 'Jamaica',
    flag: '🇯🇲',
    stateLabel: 'Parroquia',
    states: [
      'Kingston',
      'St. Andrew',
      'St. Thomas',
      'Portland',
      'St. Mary',
      'St. Ann',
      'Trelawny',
      'St. James',
      'Hanover',
      'Westmoreland',
      'St. Elizabeth',
      'Manchester',
      'Clarendon',
      'St. Catherine',
    ],
  },
  {
    code: 'TT',
    name: 'Trinidad y Tobago',
    flag: '🇹🇹',
    stateLabel: 'Región / isla',
    states: [
      'Port of Spain',
      'San Fernando',
      'Chaguanas',
      'Arima',
      'Point Fortin',
      'Tobago',
      'Couva–Tabaquite–Talparo',
      'Diego Martin',
      'Mayaro–Rio Claro',
      'Penal–Debe',
      'Princes Town',
      'Sangre Grande',
      'San Juan–Laventille',
      'Siparia',
      'Tunapuna–Piarco',
    ],
  },
  {
    code: 'BS',
    name: 'Bahamas',
    flag: '🇧🇸',
    stateLabel: 'Isla / distrito',
    states: [
      'New Providence',
      'Grand Bahama',
      'Abaco',
      'Andros',
      'Eleuthera',
      'Exuma',
      'Bimini',
      'Cat Island',
      'Long Island',
      'Other islands',
    ],
  },
  {
    code: 'BB',
    name: 'Barbados',
    flag: '🇧🇧',
    stateLabel: 'Parroquia',
    states: [
      'Christ Church',
      'Saint Andrew',
      'Saint George',
      'Saint James',
      'Saint John',
      'Saint Joseph',
      'Saint Lucy',
      'Saint Michael',
      'Saint Peter',
      'Saint Philip',
      'Saint Thomas',
    ],
  },
  {
    code: 'PR',
    name: 'Puerto Rico',
    flag: '🇵🇷',
    stateLabel: 'Municipio (principales)',
    states: [
      'San Juan',
      'Bayamón',
      'Carolina',
      'Ponce',
      'Caguas',
      'Guaynabo',
      'Mayagüez',
      'Arecibo',
      'Toa Baja',
      'Trujillo Alto',
      'Otro municipio',
    ],
  },
  {
    code: 'CO',
    name: 'Colombia',
    flag: '🇨🇴',
    stateLabel: 'Departamento',
    states: [
      'Amazonas',
      'Antioquia',
      'Arauca',
      'Atlántico',
      'Bogotá D.C.',
      'Bolívar',
      'Boyacá',
      'Caldas',
      'Caquetá',
      'Casanare',
      'Cauca',
      'Cesar',
      'Chocó',
      'Córdoba',
      'Cundinamarca',
      'Guainía',
      'Guaviare',
      'Huila',
      'La Guajira',
      'Magdalena',
      'Meta',
      'Nariño',
      'Norte de Santander',
      'Putumayo',
      'Quindío',
      'Risaralda',
      'San Andrés y Providencia',
      'Santander',
      'Sucre',
      'Tolima',
      'Valle del Cauca',
      'Vaupés',
      'Vichada',
    ],
  },
  {
    code: 'VE',
    name: 'Venezuela',
    flag: '🇻🇪',
    stateLabel: 'Estado',
    states: [
      'Amazonas',
      'Anzoátegui',
      'Apure',
      'Aragua',
      'Barinas',
      'Bolívar',
      'Carabobo',
      'Cojedes',
      'Delta Amacuro',
      'Distrito Capital',
      'Falcón',
      'Guárico',
      'Lara',
      'Mérida',
      'Miranda',
      'Monagas',
      'Nueva Esparta',
      'Portuguesa',
      'Sucre',
      'Táchira',
      'Trujillo',
      'Vargas',
      'Yaracuy',
      'Zulia',
    ],
  },
  {
    code: 'GY',
    name: 'Guyana',
    flag: '🇬🇾',
    stateLabel: 'Región',
    states: [
      'Barima-Waini',
      'Pomeroon-Supenaam',
      'Essequibo Islands-West Demerara',
      'Demerara-Mahaica',
      'Mahaica-Berbice',
      'East Berbice-Corentyne',
      'Cuyuni-Mazaruni',
      'Potaro-Siparuni',
      'Upper Takutu-Upper Essequibo',
      'Upper Demerara-Berbice',
    ],
  },
  {
    code: 'SR',
    name: 'Surinam',
    flag: '🇸🇷',
    stateLabel: 'Distrito',
    states: [
      'Brokopondo',
      'Commewijne',
      'Coronie',
      'Marowijne',
      'Nickerie',
      'Para',
      'Paramaribo',
      'Saramacca',
      'Sipaliwini',
      'Wanica',
    ],
  },
  {
    code: 'BR',
    name: 'Brasil',
    flag: '🇧🇷',
    stateLabel: 'Estado',
    states: [
      'Acre',
      'Alagoas',
      'Amapá',
      'Amazonas',
      'Bahia',
      'Ceará',
      'Distrito Federal',
      'Espírito Santo',
      'Goiás',
      'Maranhão',
      'Mato Grosso',
      'Mato Grosso do Sul',
      'Minas Gerais',
      'Pará',
      'Paraíba',
      'Paraná',
      'Pernambuco',
      'Piauí',
      'Rio de Janeiro',
      'Rio Grande do Norte',
      'Rio Grande do Sul',
      'Rondônia',
      'Roraima',
      'Santa Catarina',
      'São Paulo',
      'Sergipe',
      'Tocantins',
    ],
  },
  {
    code: 'EC',
    name: 'Ecuador',
    flag: '🇪🇨',
    stateLabel: 'Provincia',
    states: [
      'Azuay',
      'Bolívar',
      'Cañar',
      'Carchi',
      'Chimborazo',
      'Cotopaxi',
      'El Oro',
      'Esmeraldas',
      'Galápagos',
      'Guayas',
      'Imbabura',
      'Loja',
      'Los Ríos',
      'Manabí',
      'Morona Santiago',
      'Napo',
      'Orellana',
      'Pastaza',
      'Pichincha',
      'Santa Elena',
      'Santo Domingo de los Tsáchilas',
      'Sucumbíos',
      'Tungurahua',
      'Zamora Chinchipe',
    ],
  },
  {
    code: 'PE',
    name: 'Perú',
    flag: '🇵🇪',
    stateLabel: 'Departamento',
    states: [
      'Amazonas',
      'Áncash',
      'Apurímac',
      'Arequipa',
      'Ayacucho',
      'Cajamarca',
      'Callao',
      'Cusco',
      'Huancavelica',
      'Huánuco',
      'Ica',
      'Junín',
      'La Libertad',
      'Lambayeque',
      'Lima',
      'Loreto',
      'Madre de Dios',
      'Moquegua',
      'Pasco',
      'Piura',
      'Puno',
      'San Martín',
      'Tacna',
      'Tumbes',
      'Ucayali',
    ],
  },
  {
    code: 'BO',
    name: 'Bolivia',
    flag: '🇧🇴',
    stateLabel: 'Departamento',
    states: [
      'Chuquisaca',
      'Cochabamba',
      'El Beni',
      'La Paz',
      'Oruro',
      'Pando',
      'Potosí',
      'Santa Cruz',
      'Tarija',
    ],
  },
  {
    code: 'PY',
    name: 'Paraguay',
    flag: '🇵🇾',
    stateLabel: 'Departamento',
    states: [
      'Asunción',
      'Concepción',
      'San Pedro',
      'Cordillera',
      'Guairá',
      'Caaguazú',
      'Caazapá',
      'Itapúa',
      'Misiones',
      'Paraguarí',
      'Alto Paraná',
      'Central',
      'Ñeembucú',
      'Amambay',
      'Canindeyú',
      'Presidente Hayes',
      'Alto Paraguay',
      'Boquerón',
    ],
  },
  {
    code: 'CL',
    name: 'Chile',
    flag: '🇨🇱',
    stateLabel: 'Región',
    states: [
      'Arica y Parinacota',
      'Tarapacá',
      'Antofagasta',
      'Atacama',
      'Coquimbo',
      'Valparaíso',
      'Metropolitana de Santiago',
      "O'Higgins",
      'Maule',
      'Ñuble',
      'Biobío',
      'La Araucanía',
      'Los Ríos',
      'Los Lagos',
      'Aysén',
      'Magallanes',
    ],
  },
  {
    code: 'AR',
    name: 'Argentina',
    flag: '🇦🇷',
    stateLabel: 'Provincia',
    states: [
      'Buenos Aires',
      'CABA',
      'Catamarca',
      'Chaco',
      'Chubut',
      'Córdoba',
      'Corrientes',
      'Entre Ríos',
      'Formosa',
      'Jujuy',
      'La Pampa',
      'La Rioja',
      'Mendoza',
      'Misiones',
      'Neuquén',
      'Río Negro',
      'Salta',
      'San Juan',
      'San Luis',
      'Santa Cruz',
      'Santa Fe',
      'Santiago del Estero',
      'Tierra del Fuego',
      'Tucumán',
    ],
  },
  {
    code: 'UY',
    name: 'Uruguay',
    flag: '🇺🇾',
    stateLabel: 'Departamento',
    states: [
      'Artigas',
      'Canelones',
      'Cerro Largo',
      'Colonia',
      'Durazno',
      'Flores',
      'Florida',
      'Lavalleja',
      'Maldonado',
      'Montevideo',
      'Paysandú',
      'Río Negro',
      'Rivera',
      'Rocha',
      'Salto',
      'San José',
      'Soriano',
      'Tacuarembó',
      'Treinta y Tres',
    ],
  },
];

export function getCountry(code: string): CountryDef | undefined {
  return COUNTRIES.find((c) => c.code === code);
}

export function statesForCountry(code: string): string[] {
  return getCountry(code)?.states ?? [];
}

export function countryLabel(c: CountryDef): string {
  return `${c.flag} ${c.name}`;
}
